# 初步创建用户表
USE coderhub;
CREATE TABLE `users`  (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(30)  NOT NULL UNIQUE,
  `password` VARCHAR(50)  NOT NULL,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
# 插入数据
INSERT INTO users (NAME,PASSWORD) VALUES ('张三','123abc')

#根据用户名查询用户信息
SELECT * FROM users WHERE NAME='张三';